Mazars-Tech/AD_Miner

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Add two templates for issues : 
- Bug report
- Feature request
=> docs: add issues templates

.github/workflows/release.yml
Reverts Mazars-Tech/AD_Miner#29
=> Revert "build: update release workflow to bump version in pyproject.toml when releasing"

ad_miner/sources/html/bootstrap/css/search_bar.css, ad_miner/sources/html/templates/main_header.html, ad_miner/sources/js/search_bar.js, ad_miner/sources/modules/main_page.py
Adds a search bar on the main page to find controls more easily.
=> feat: add a search bar on the main page

ad_miner/sources/modules/config.json, ad_miner/sources/modules/neo4j_class.py
Fix for #16 
The request was unused anyway.
=> fix: remove unused request that could cause some crash

ad_miner/sources/modules/users.py
fix https://github.com/Mazars-Tech/AD_Miner/issues/41
=> fix: bug with url encoding

ad_miner/sources/modules/domains.py
This adds a fail safe check in case all domains were not collected for da to da.
=> fix: quick fail safe for da to da in case domains were not collected

ad_miner/__main__.py
Fix AD Miner crash when disabling a request in config.json due to typo in code.
=> fix: code typo crash AD Miner when disabling a request in config.json

ad_miner/sources/modules/objects.py
Small rework for dcsync. It adds another column to show the full path to dcsync instead of creating a virtual node.
It also fixes the case when the object can dcsync on another domain.
=> feat: small rework for dcsync control

ad_miner/sources/modules/computers.py
Fix bug reported on discord about obsolete OS not getting tagged because of the case.
=> fix: fix OS format for obsolete OS

ad_miner/sources/modules/domains.py, ad_miner/sources/modules/requests.json
- Splits schema and enterprise admin column
- Splits key admin and enterprise key admin column
- Adds protected users column
=> feat: split schema and key admin + add protected users on DA page

ad_miner/sources/html/bootstrap/css/main_page.css, ad_miner/sources/js/search_bar.js, ad_miner/sources/modules/config.json
- Highlights hovered controls of the drop down list in the circle
- Closes the searchbar when clicking elsewhere
=> Improve search bar

ad_miner/sources/modules/neo4j_class.py
=> Extend pre request

ad_miner/sources/html/components/smolcard/smolcard_header.html, ad_miner/sources/html/templates/cards_modal_header.html, ad_miner/sources/modules/main_page.py
=> feat: add log scale button for evolution graph

ad_miner/sources/modules/domains.py, ad_miner/sources/modules/requests.json
Resolves #75 
* ghost DC displayed first
*  red ghost icon
*  add last_logon column
=> feat: ghost DC displayed first in DC list, add lastlogon column

ad_miner/sources/modules/main_page.py, ad_miner/sources/modules/rating.py
=> fix: rating now take into account the oldest krbtgt password change

ad_miner/sources/html/bootstrap/css/custom.css, ad_miner/sources/html/bootstrap/css/main_page.css, ad_miner/sources/html/components/smolcard/smolcard_header.html, ad_miner/sources/modules/description.json, ad_miner/sources/modules/smolcard_class.py
=> feat: add small evolution percentage

ad_miner/sources/modules/requests.json
Based on objectid rather than name attribute
=> fix: request set is_adcs

ad_miner/sources/modules/domains.py, ad_miner/sources/modules/neo4j_class.py, ad_miner/sources/modules/requests.json
* more precise neo4j cleaning request
* add template, comments and better variables in requests.json
* remove never called request :(
* add domains to domain page if no trust is returned
* fix: empty 'computer without LAPS' query for uppercase OS name
* fix: domain controllers OS not displayed when uppercase
Fix #102 
Fix #103
=> Small bug fix

README.md, ad_miner/__main__.py
modify sorting of sections in README for structure (group community related topics at the end)
add guidelines on creating a synthetic dataset to test ADMiner, using DBCreator
=> docs: Modifications on README.md for readability and guidelines to generate synthetic data.

ad_miner/sources/modules/requests.json
fix https://github.com/Mazars-Tech/AD_Miner/issues/120
=> fix: bug with u.name

ad_miner/sources/html/bootstrap/css/main_page.css, ad_miner/sources/html/templates/main_header.html, ad_miner/sources/modules/main_page.py, ad_miner/sources/modules/page_class.py, ad_miner/sources/modules/utils.py
* switch on prem / azure is white and AD Miner is always displayed
* fix windows compatibility of OU control
* fix potential broken links when page name contains "/"
=> Small fixes

ad_miner/sources/js/graph.js, ad_miner/sources/modules/graph_class.py
Small style tweak to make edges that link two nodes from different domains more visible.
=> Stylised edges between different domains

README.md
Add a small prerequisites section to the README.md
=> docs: Add prerequisites to readme.md

ad_miner/sources/modules/requests.json
- Fixing kerberoastable request to remove gmsa accounts from kerberoastable accounts
=> fix: remove gmsa account from kerberoastable accounts

ad_miner/sources/modules/config.json, ad_miner/sources/modules/requests.json
- Fixing request computers_members_high_privilege by changing "highvalue" attribute (not used anymore in BHCE) by custom attribute "is_da"
- New request to set isacl true for ADCSESC edges
=> fix: request computers_members_high_privilege and isacl for ADCS

ad_miner/sources/modules/config.json, ad_miner/sources/modules/requests.json
- New request : new attribute to flag MSOL accounts is_msol = true and is_da = true
- Update request : Remove MSOL accounts from domain admins
=> fix: remove MSOL from path candidates

ad_miner/sources/modules/requests.json
-  Better cleaning request (deleting new/other attributes)
-  New attribute dac in case a computer is domain admin
=> fix: fix crash when a computer is member of DA

.gitignore, .vscode/settings.json, ad_miner/__main__.py, ad_miner/sources/modules/utils.py
=> feat: add cache files warning

ad_miner/sources/modules/requests.json
New pre-request to check for group objects without domain attribute and fix it
=> fix: Add new check for Group objects without domain attribute

ad_miner/sources/modules/controls/server_users_could_be_admin.py, ad_miner/sources/modules/controls/users_password_not_required.py
=> Typos post refacto

ad_miner/sources/modules/neo4j_class.py, ad_miner/sources/modules/requests.json
- fix parallelism issues
- remove duplicates in the "users could compromise a server" grid
=> fix: admin on servers request and remove duplicates
